version: "3.8"
services:
  db:
    image: mariadb:10.4.27
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: movie_management
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma db push && npm run start:prod"
